name: Feature Branch

on:
  push:
    branches-ignore:
      - 'master'
      - 'release*'

  pull_request:
    types: [opened, synchronize, reopened]

jobs:

  test:
    name: Unit Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
      - name: Maven Clean Package
        run: mvn -B clean package -DskipTests
      - name: Maven Clean Verify
        run: mvn -B clean verify

